# Site settings
author: Ashlee Scott
title: 
header-img: img/home-bg.png
email: ashlee.scott@flatironschool.com
copyright_name: Ashlee Scott
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ashleesc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
